[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
cnft_escrow = "9PXknQSJw9Roe3xrogPW8pr1ztNFcBiJbFzEz8EyFEN6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../../devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/cnft-escrow.ts"
